image: maven:3.8.7-eclipse-temurin-19

stages:
  - test

testing_phase:
  stage: test

  script:
    - echo "Testing..."
    - "mvn test"

  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml